### ISSUE TITLE
CSS Repetition

### ISSUE THREAD

**Issue by miketruax** [mikejunt/week-1-project#3]
Take a look at any of your styling that can overlap such as the below:

``` css
.return-link:link {
    color: white;
}
.return-link:visited {
    color: white;
}
```

Instead of that you can just do with a multi selector instead of having two full declarations. That can clean up your code in a couple places to look like: 

``` css
.return-link:link, .return-link:visited {
    color: white;
}
```
